# Site settings
title: Konstantin Zaremski
email: your-email@example.com
description: >-
  Konstantin Zaremski is a fast learning and technology obsessed young professional
  with experience and exposure covering the gamut of web and related technologies
  from the front end to the back end.
baseurl: ""
url: "https://konstantin.zarem.ski"

# Build settings
markdown: kramdown
permalink: pretty

# Collections
collections:
  projects:
    output: true
    permalink: /projects/:name/

# Defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "Konstantin Zaremski"
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "project"
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - package.json
  - package-lock.json
  - README.md

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag
